"""
llm_rl_agent.py

LLM-enhanced PPO agent.

This agent extends the baseline PPO agent with high-level
procedural guidance generated by an LLM.

Supported experiment modes:

    NONE
        Behaves like standard PPO.

    INPUT
        LLM guidance is appended to the PPO observation.

    REWARD_SHAPING
        PPO observation is unchanged.
        FinanceEnvironment adds a positive guidance bonus when
        the LLM-generated procedure is followed.

    INPUT_AND_REWARD
        Uses both:
            - guidance as policy input
            - positive reward shaping

Important architectural separation
----------------------------------

LLMRLAgent:
    - calls the LLM planner
    - stores the generated procedure
    - constructs guided observations
    - performs PPO learning

FinanceEnvironment:
    - executes finance actions
    - tracks procedure progress
    - calculates base rewards
    - applies negative penalties
    - applies guidance bonuses
    - detects task completion
    - records backend episodes

The LLM does NOT block PPO actions.

PPO remains free to select any action from the complete
action space.
"""

from typing import Optional

import numpy as np

from agents.ppo_agent import PPOAgent

from config.config import config

from llm.planner import LLMPlanner


class LLMRLAgent(PPOAgent):
    """
    PPO agent enhanced with LLM-generated procedural guidance.
    """

    # ==========================================================
    # Supported Guidance Modes
    # ==========================================================

    VALID_GUIDANCE_MODES = {
        "NONE",
        "INPUT",
        "REWARD_SHAPING",
        "INPUT_AND_REWARD",
    }

    # ==========================================================
    # Constructor
    # ==========================================================

    def __init__(
        self,
        observation_size: int,
        action_size: int,
        planner: Optional[LLMPlanner] = None,
    ):

        # ------------------------------------------------------
        # Base environment observation size.
        #
        # Current FinanceEnvironment:
        #
        #     13 binary state values
        # ------------------------------------------------------

        self.base_observation_size = int(observation_size)

        self.guidance_size = int(action_size)

        # ======================================================
        # Guidance Configuration
        # ======================================================

        self.guidance_mode = str(config.experiment.GUIDANCE_MODE).upper()

        if self.guidance_mode not in self.VALID_GUIDANCE_MODES:

            raise ValueError(
                "Unsupported guidance mode: "
                f"{self.guidance_mode}. "
                "Expected one of: "
                f"{sorted(self.VALID_GUIDANCE_MODES)}"
            )

        # ------------------------------------------------------
        # Does the PPO network receive LLM guidance?
        # ------------------------------------------------------

        self.use_input_guidance = self.guidance_mode in {
            "INPUT",
            "INPUT_AND_REWARD",
        }

        # ------------------------------------------------------
        # Does the environment apply guidance reward?
        #
        # The environment/reward processor actually performs
        # the reward calculation.
        # ------------------------------------------------------

        self.use_reward_guidance = self.guidance_mode in {
            "REWARD_SHAPING",
            "INPUT_AND_REWARD",
        }

        # ======================================================
        # PPO Input Dimension
        # ======================================================

        if self.use_input_guidance:

            policy_observation_size = self.base_observation_size + self.guidance_size

        else:

            policy_observation_size = self.base_observation_size

        self.policy_observation_size = policy_observation_size

        # ======================================================
        # Initialize Standard PPO
        # ======================================================

        super().__init__(
            observation_size=self.policy_observation_size,
            action_size=action_size,
        )

        # ======================================================
        # LLM Planner
        # ======================================================

        self.planner = planner if planner is not None else LLMPlanner()

        # ======================================================
        # Current Episode Plan
        # ======================================================

        self.current_plan = []

        self.current_plan_ids = []

        self.current_prerequisites = {}

        self.current_prompt_version = None

        self.current_plan_cached = False

        self.current_plan_latency_ms = 0.0

        self.current_raw_response = None

        # ======================================================
        # LLM Experiment Statistics
        # ======================================================

        self.planned_episodes = 0

        self.cached_plan_episodes = 0

        self.uncached_plan_episodes = 0

        self.planning_failures = 0

        self.total_episode_planning_time_ms = 0.0

    # ==========================================================
    # Planning
    # ==========================================================

    def plan(
        self,
        state,
        goal=None,
        force_refresh=False,
    ):
        """
        Generate a high-level LLM procedure.

        Overrides BaseAgent.plan().

        Parameters
        ----------
        state : dict

            Environment state supplied to the planner.

        goal : str, optional

            Task goal.

            Defaults to:
                config.agent.TASK

        force_refresh : bool

            Ignore the cache and call Ollama again.

        Returns
        -------
        dict

            Planner result.
        """

        if goal is None:

            goal = config.agent.TASK

        result = self.planner.plan(
            goal=goal,
            state=state,
            force_refresh=force_refresh,
        )

        # ======================================================
        # Planner Failure
        # ======================================================

        if not result.get(
            "success",
            False,
        ):

            self.planning_failures += 1

            self._clear_current_plan()

            return result

        # ======================================================
        # Store Current Plan
        # ======================================================

        self.current_plan = list(
            result.get(
                "action_names",
                [],
            )
        )

        self.current_plan_ids = [
            int(action)
            for action in result.get(
                "action_ids",
                [],
            )
        ]

        self.current_prerequisites = dict(
            result.get(
                "prerequisites",
                {},
            )
        )

        # ======================================================
        # Prompt / Cache Metadata
        # ======================================================

        self.current_prompt_version = (
            result.get(
                "prompt_version"
            )
        )

        self.current_plan_cached = bool(
            result.get(
                "cached",
                False,
            )
        )

        # ------------------------------------------------------
        # Episode-level planning latency
        #
        # For cache hits no new LLM generation occurred, so the
        # episode records zero LLM-generation latency.
        #
        # The original uncached generation latency can still be
        # measured through planner-level metrics.
        # ------------------------------------------------------

        if self.current_plan_cached:

            self.current_plan_latency_ms = 0.0

        else:

            self.current_plan_latency_ms = float(
                result.get(
                    "latency_ms",
                    0.0,
                )
                or 0.0
            )

        self.current_raw_response = (
            result.get(
                "raw_response"
            )
        )

        # ======================================================
        # Statistics
        # ======================================================

        self.planned_episodes += 1

        if self.current_plan_cached:

            self.cached_plan_episodes += 1

        else:

            self.uncached_plan_episodes += 1

            self.total_episode_planning_time_ms += self.current_plan_latency_ms

        return result

    # ==========================================================
    # Prepare Episode
    # ==========================================================

    def prepare_episode(
        self,
        env,
        seed=None,
        phase=None,
        experiment_name=None,
        goal=None,
        planning_state=None,
        force_refresh_plan=False,
    ):
        """
        Prepare one complete LLM + PPO episode.

        This method:

            1. constructs a fresh planning state
            2. calls the LLM planner
            3. passes the LLM plan into FinanceEnvironment.reset()
            4. starts agent-side episode tracking
            5. creates the initial PPO observation

        This should replace the normal:

            state = env.reset()
            agent.start_episode()

        sequence used by baseline PPO.

        Returns
        -------
        np.ndarray
            Initial observation for LLM + PPO.
        """

        # ======================================================
        # Goal
        # ======================================================

        if goal is None:

            goal = getattr(
                env,
                "goal",
                config.agent.TASK,
            )

        # ======================================================
        # Initial Planning State
        #
        # Planning happens BEFORE env.reset(), because reset()
        # starts the backend Episode and we want llmPlan stored
        # in that Episode from the beginning.
        # ======================================================

        if planning_state is None:

            if hasattr(
                env,
                "_initial_state",
            ):

                planning_state = env._initial_state()

            else:

                planning_state = {
                    "get_invoices": False,
                    "check_duplicate": False,
                    "check_supplier": False,
                    "approve_invoices": False,
                    "pay_invoices": False,
                    "check_budget": False,
                    "generate_report": False,
                    "check_payment_completed": False,
                    "has_paid_invoices": False,
                    "has_rejected_invoices": False,
                    "has_pending_approval_invoices": False,
                    "has_approved_invoices": False,
                    "task_completed": False,
                }

        # ======================================================
        # LLM Planning
        # ======================================================

        plan_result = self.plan(
            state=planning_state,
            goal=goal,
            force_refresh=force_refresh_plan,
        )

        if not plan_result.get(
            "success",
            False,
        ):

            error = plan_result.get(
                "error",
                "Unknown planner error.",
            )

            raise RuntimeError("LLM planning failed: " f"{error}")

        if not self.current_plan:

            raise RuntimeError("LLM planner returned an empty plan.")

        # ======================================================
        # Episode Metadata
        # ======================================================

        if phase is None:

            phase = config.experiment.PHASE

        if experiment_name is None:

            experiment_name = config.experiment.EXPERIMENT_NAME

        # ======================================================
        # Reset Finance Environment
        #
        # The generated plan is supplied BEFORE the backend
        # Episode is started.
        # ======================================================

        base_observation = env.reset(
            seed=seed,
            options={
                # ==================================================
                # Agent / Experiment
                # ==================================================
                "agent_type": "LLM_RL",
                "algorithm": "PPO",
                "goal": goal,
                "phase": phase,
                "experiment_name": experiment_name,
                # ==================================================
                # LLM
                # ==================================================
                "llm_model": config.llm.MODEL,
                "prompt_version": self.current_prompt_version,
                "llm_plan_cached": self.current_plan_cached,
                "llm_planning_time_ms": self.current_plan_latency_ms,
                "guidance_mode": self.guidance_mode,
                "llm_plan": self.current_plan,
            },
        )

        # ======================================================
        # Agent Episode Counter
        # ======================================================

        super().start_episode()

        # ======================================================
        # PPO Observation
        # ======================================================

        return self.build_observation(
            base_observation=base_observation,
            env=env,
        )

    # ==========================================================
    # Observation Construction
    # ==========================================================

    def build_observation(
        self,
        base_observation,
        env=None,
        guidance_vector=None,
    ):
        """
        Build the PPO network input.

        REWARD_SHAPING
        --------------

            observation =
                base state

            Current size:
                13

        INPUT / INPUT_AND_REWARD
        ------------------------

            observation =
                base state
                +
                LLM guidance vector

            Current size:
                13 + 8 = 21
        """

        base_observation = np.asarray(
            base_observation,
            dtype=np.float32,
        ).reshape(-1)

        # ======================================================
        # Validate Base State
        # ======================================================

        if base_observation.shape[0] != self.base_observation_size:

            raise ValueError(
                "Expected base observation size "
                f"{self.base_observation_size}, "
                "received "
                f"{base_observation.shape[0]}."
            )

        # ======================================================
        # No Input Guidance
        # ======================================================

        if not self.use_input_guidance:

            return base_observation.copy()

        # ======================================================
        # Guidance Vector
        # ======================================================

        if guidance_vector is None:

            if env is None:

                raise ValueError(
                    "env or guidance_vector must be "
                    "provided when using LLM input guidance."
                )

            guidance_vector = env.get_guidance_vector()

        guidance_vector = np.asarray(
            guidance_vector,
            dtype=np.float32,
        ).reshape(-1)

        # ======================================================
        # Validate Guidance
        # ======================================================

        if guidance_vector.shape[0] != self.guidance_size:

            raise ValueError(
                "Expected guidance vector size "
                f"{self.guidance_size}, "
                "received "
                f"{guidance_vector.shape[0]}."
            )

        # ======================================================
        # Combined PPO State
        # ======================================================

        observation = np.concatenate(
            [
                base_observation,
                guidance_vector,
            ]
        ).astype(np.float32)

        if observation.shape[0] != self.policy_observation_size:

            raise RuntimeError("Guided observation has incorrect size.")

        return observation

    # ==========================================================
    # Environment Step
    # ==========================================================

    def step_environment(
        self,
        env,
        action,
    ):
        """
        Execute one environment action and convert the returned
        base observation into the correct PPO observation.

        This method does NOT alter the reward.

        FinanceEnvironment has already applied:

            - action reward
            - negative business penalties
            - task-completion reward
            - optional guidance bonus
        """

        (
            base_next_state,
            reward,
            done,
            info,
        ) = env.step(action)

        # ======================================================
        # Guidance AFTER Current Action
        #
        # FinanceEnvironment updates ProcedureTracker during
        # env.step().
        #
        # Therefore info["guidance_vector"] represents the NEXT
        # recommended action.
        # ======================================================

        guidance_vector = info.get("guidance_vector")

        next_state = self.build_observation(
            base_observation=base_next_state,
            env=env,
            guidance_vector=guidance_vector,
        )

        return (
            next_state,
            reward,
            done,
            info,
        )

    # ==========================================================
    # Current Guidance
    # ==========================================================

    def get_current_guidance(
        self,
        env,
    ):
        """
        Return the current one-hot guidance vector.
        """

        return np.asarray(
            env.get_guidance_vector(),
            dtype=np.float32,
        )

    # ==========================================================
    # Current Plan
    # ==========================================================

    def get_current_plan(
        self,
    ):

        return self.current_plan.copy()

    def get_current_plan_ids(
        self,
    ):

        return self.current_plan_ids.copy()

    def get_current_prerequisites(
        self,
    ):

        return dict(self.current_prerequisites)

    # ==========================================================
    # Clear Plan
    # ==========================================================

    def _clear_current_plan(
        self,
    ):

        self.current_plan = []

        self.current_plan_ids = []

        self.current_prerequisites = {}

        self.current_prompt_version = None

        self.current_plan_cached = False

        self.current_plan_latency_ms = 0.0

        self.current_raw_response = None

    # ==========================================================
    # Planner Metrics
    # ==========================================================

    def get_llm_metrics(
        self,
    ):
        """
        Return LLM-specific experiment metrics.
        """

        planner_metrics = self.planner.get_metrics()

        cache_metrics = planner_metrics.get(
            "cache",
            {},
        )

        return {
            "model": config.llm.MODEL,
            "guidance_mode": self.guidance_mode,
            "planned_episodes": self.planned_episodes,
            "planning_failures": self.planning_failures,
            "cached_plan_episodes": self.cached_plan_episodes,
            "uncached_plan_episodes": self.uncached_plan_episodes,
            "uncached_planning_time_ms": self.total_episode_planning_time_ms,
            "planner_calls": planner_metrics.get(
                "total_calls",
                0,
            ),
            "planner_successful_calls": planner_metrics.get(
                "successful_calls",
                0,
            ),
            "planner_failed_calls": planner_metrics.get(
                "failed_calls",
                0,
            ),
            "average_llm_latency_ms": planner_metrics.get(
                "average_latency_ms",
                0.0,
            ),
            "total_llm_latency_ms": planner_metrics.get(
                "total_latency_ms",
                0.0,
            ),
            "cache_hits": cache_metrics.get(
                "hits",
                0,
            ),
            "cache_misses": cache_metrics.get(
                "misses",
                0,
            ),
            "cache_writes": cache_metrics.get(
                "writes",
                0,
            ),
        }

    # ==========================================================
    # Agent Information
    # ==========================================================

    def get_info(
        self,
    ):

        info = super().get_info()

        info.update(
            {
                "agent_type": "LLM_RL",
                "llm_model": config.llm.MODEL,
                "guidance_mode": self.guidance_mode,
                "use_input_guidance": self.use_input_guidance,
                "use_reward_guidance": self.use_reward_guidance,
                "base_observation_size": self.base_observation_size,
                "guidance_size": self.guidance_size,
                "policy_observation_size": self.policy_observation_size,
                "current_plan": self.get_current_plan(),
                "current_plan_ids": self.get_current_plan_ids(),
                "current_plan_cached": self.current_plan_cached,
                "current_prompt_version": self.current_prompt_version,
                "current_plan_latency_ms": self.current_plan_latency_ms,
                "llm_metrics": self.get_llm_metrics(),
            }
        )

        return info

    # ==========================================================
    # Close
    # ==========================================================

    def close(
        self,
    ):
        """
        Close the planner HTTP session.
        """

        if self.planner is not None:

            self.planner.close()
