"""
procedure_tracker.py

Tracks progress through an LLM-generated action procedure.

Used by LLM + PPO for:

    - guidance input
    - procedure-following reward shaping
    - experiment logging

The tracker contains NO finance business rules.

It only follows the sequence generated by the LLM.

Example:

    LLM plan:
        [0, 1, 2, 3, 5, 4, 7]

The tracker simply interprets this as:

    0 -> 1 -> 2 -> 3 -> 5 -> 4 -> 7
"""

from __future__ import annotations

from typing import Iterable, List, Optional


class ProcedureTracker:

    def __init__(
        self,
        procedure: Optional[Iterable[int]] = None,
        action_dim: int = 0,
    ):

        self.action_dim = int(action_dim)

        self.procedure: List[int] = []

        self.executed: List[bool] = []

        self.set_procedure(procedure or [])

    # ==========================================================
    # Procedure Setup
    # ==========================================================

    def set_procedure(
        self,
        procedure: Iterable[int],
    ):

        procedure = [int(action) for action in procedure]

        # ------------------------------------------------------
        # Validate action IDs
        # ------------------------------------------------------

        for action in procedure:

            if action < 0 or action >= self.action_dim:

                raise ValueError(
                    "Invalid action "
                    f"{action} in LLM procedure. "
                    f"Action dimension is "
                    f"{self.action_dim}."
                )

        self.procedure = procedure

        self.executed = [False for _ in self.procedure]

    # ==========================================================
    # Reset
    # ==========================================================

    def reset(
        self,
        procedure=None,
    ):

        if procedure is not None:

            self.set_procedure(procedure)

            return

        self.executed = [False for _ in self.procedure]

    # ==========================================================
    # Clear
    # ==========================================================

    def clear(
        self,
    ):

        self.procedure = []

        self.executed = []

    # ==========================================================
    # Basic Information
    # ==========================================================

    def has_procedure(
        self,
    ):

        return bool(self.procedure)

    def get_procedure(
        self,
    ):

        return self.procedure.copy()

    def get_execution_status(
        self,
    ):

        return self.executed.copy()

    # ==========================================================
    # Current Procedure Position
    # ==========================================================

    def get_next_index(
        self,
    ) -> Optional[int]:

        for (
            index,
            completed,
        ) in enumerate(self.executed):

            if not completed:

                return index

        return None

    def get_next_action(
        self,
    ) -> Optional[int]:

        index = self.get_next_index()

        if index is None:

            return None

        return self.procedure[index]

    # ==========================================================
    # Procedure Check
    # ==========================================================

    def is_expected_action(
        self,
        action,
    ) -> Optional[bool]:
        """
        Returns:

            None
                no LLM procedure exists

            True
                action is currently recommended

            False
                action differs from current recommendation
        """

        if not self.has_procedure():

            return None

        expected_action = self.get_next_action()

        if expected_action is None:

            return False

        return int(action) == expected_action

    # ==========================================================
    # Mark Complete
    # ==========================================================

    def mark_completed(
        self,
        action,
    ):

        expected = self.get_next_action()

        if expected is None:

            return False

        if int(action) != expected:

            return False

        index = self.get_next_index()

        if index is None:

            return False

        self.executed[index] = True

        return True

    # ==========================================================
    # Check Action
    # ==========================================================

    def check_action(
        self,
        action,
        action_succeeded,
    ) -> Optional[bool]:
        """
        Determine whether the selected action successfully
        followed the current LLM procedure.

        Procedure progress advances only when:

            selected action == expected action
            AND
            action succeeded

        A successful no-op may still advance the procedure,
        because the LLM recommendation was attempted.

        RewardProcessor separately decides whether such a no-op
        deserves a reward.

        Returns
        -------

        None:
            No LLM procedure exists.

        True:
            Expected action was selected and succeeded.

        False:
            Action deviated from plan or failed.
        """

        expected = self.is_expected_action(action)

        if expected is None:

            return None

        if not expected:

            return False

        if not action_succeeded:

            return False

        self.mark_completed(action)

        return True

    # ==========================================================
    # Guidance Vector
    # ==========================================================

    def get_guidance(
        self,
    ) -> List[float]:
        """
        One-hot vector representing the next LLM-recommended
        action.

        Example:

            action_dim = 8
            next action = 5

            [
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0
            ]

        If no procedure exists or the plan is complete,
        the vector contains only zeros.
        """

        guidance = [0.0 for _ in range(self.action_dim)]

        next_action = self.get_next_action()

        if next_action is None:

            return guidance

        guidance[next_action] = 1.0

        return guidance

    # ==========================================================
    # Progress
    # ==========================================================

    def completed_count(
        self,
    ):

        return sum(self.executed)

    def remaining_count(
        self,
    ):

        return len(self.procedure) - self.completed_count()

    def is_complete(
        self,
    ):

        return bool(self.executed) and all(self.executed)

    def progress_ratio(
        self,
    ):

        if not self.procedure:

            return 0.0

        return self.completed_count() / len(self.procedure)

    # ==========================================================
    # Status
    # ==========================================================

    def get_status(
        self,
    ):

        return {
            "procedure": self.get_procedure(),
            "executed": self.get_execution_status(),
            "nextAction": self.get_next_action(),
            "nextIndex": self.get_next_index(),
            "guidance": self.get_guidance(),
            "completed": self.is_complete(),
            "completedCount": self.completed_count(),
            "remainingCount": self.remaining_count(),
            "progress": self.progress_ratio(),
        }
