export const PERMISSIONS = {
  READ_INVOICE: "READ_INVOICE",
  CREATE_INVOICE: "CREATE_INVOICE",
  UPDATE_INVOICE: "UPDATE_INVOICE",

  APPROVE_INVOICE: "APPROVE_INVOICE",
  REJECT_INVOICE: "REJECT_INVOICE",

  PAY_INVOICE: "PAY_INVOICE",
  REFUND_PAYMENT: "REFUND_PAYMENT",

  CHECK_BUDGET: "CHECK_BUDGET",

  READ_ACCOUNT: "READ_ACCOUNT",
  TRANSFER_MONEY: "TRANSFER_MONEY",

  VALIDATE_SUPPLIER: "VALIDATE_SUPPLIER",
  BLACKLIST_SUPPLIER: "BLACKLIST_SUPPLIER",

  GENERATE_REPORT: "GENERATE_REPORT",
  VIEW_AUDIT: "VIEW_AUDIT",

  RESET_ENVIRONMENT: "RESET_ENVIRONMENT",
  VIEW_STATE: "VIEW_STATE",
};
