"""
planner.py

LLM planning component for the LLM + PPO agent.

Uses Ollama to run a local Llama 3 model.

Responsibilities:
    - Connect to the local Ollama server.
    - Send planning prompts to Llama 3.
    - Return the raw LLM response.
    - Measure LLM inference latency.
    - Report whether the LLM request succeeded.

This module does NOT:
    - select RL actions
    - execute backend actions
    - calculate rewards
    - parse the LLM response
"""

import time
from typing import Any, Dict, Optional

import requests

from config.config import config


class LLMPlanner:
    """
    Communicates with a locally running Ollama Llama 3 model.
    """

    def __init__(
        self,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
        timeout: Optional[int] = None,
    ):
        """
        Initialize the Ollama planner.

        Parameters
        ----------
        base_url : str, optional
            Ollama server URL.

        model : str, optional
            Ollama model name.

        temperature : float, optional
            LLM sampling temperature.

        timeout : int, optional
            Maximum time allowed for an LLM request.
        """

        self.base_url = base_url if base_url is not None else config.llm.BASE_URL

        self.model = model if model is not None else config.llm.MODEL

        self.temperature = (
            temperature if temperature is not None else config.llm.TEMPERATURE
        )

        self.timeout = timeout if timeout is not None else config.llm.TIMEOUT

        # Remove a trailing slash so that endpoint
        # construction remains consistent.
        self.base_url = self.base_url.rstrip("/")

        self.generate_url = f"{self.base_url}/api/generate"

    # ==========================================================
    # Generate Plan
    # ==========================================================

    def generate_plan(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> Dict[str, Any]:
        """
        Send a planning request to Ollama.

        Parameters
        ----------
        system_prompt : str
            System-level instructions.

        user_prompt : str
            Current environment state and task.

        Returns
        -------
        dict
            Contains:

            response
                Raw LLM response.

            success
                Whether the request succeeded.

            latency
                LLM inference time in seconds.

            error
                Error message if the request failed.
        """

        payload = {
            "model": self.model,
            "system": system_prompt,
            "prompt": user_prompt,
            "stream": False,
            "options": {
                "temperature": self.temperature,
            },
        }

        start_time = time.perf_counter()

        try:

            response = requests.post(
                self.generate_url,
                json=payload,
                timeout=self.timeout,
            )

            latency = time.perf_counter() - start_time

            response.raise_for_status()

            data = response.json()

            llm_response = data.get(
                "response",
                "",
            ).strip()

            return {
                "response": llm_response,
                "success": True,
                "latency": latency,
                "error": None,
            }

        except requests.RequestException as exc:

            latency = time.perf_counter() - start_time

            return {
                "response": "",
                "success": False,
                "latency": latency,
                "error": str(exc),
            }

        except ValueError as exc:

            latency = time.perf_counter() - start_time

            return {
                "response": "",
                "success": False,
                "latency": latency,
                "error": (f"Invalid Ollama response: {exc}"),
            }

    # ==========================================================
    # Simple Planning Interface
    # ==========================================================

    def plan(
        self,
        prompt: str,
        system_prompt: str,
    ) -> Dict[str, Any]:
        """
        Generate a planning recommendation.

        Parameters
        ----------
        prompt : str
            Planning prompt generated by prompts.py.

        system_prompt : str
            System instructions.

        Returns
        -------
        dict
            Ollama planning result.
        """

        return self.generate_plan(
            system_prompt=system_prompt,
            user_prompt=prompt,
        )

    # ==========================================================
    # Ollama Health Check
    # ==========================================================

    def is_available(self) -> bool:
        """
        Check whether the Ollama server is available.

        Returns
        -------
        bool
            True if Ollama is reachable.
        """

        try:

            response = requests.get(
                self.base_url,
                timeout=5,
            )

            return response.ok

        except requests.RequestException:

            return False
